### ISSUE TITLE
Search for the project

### ISSUE THREAD

**Issue by RaspY737** [PipouTeam/CUBE-CESI#7]
# Unit and Integration tests
We can use the `PHPUnit` framework. [Doc here](https://docs.phpunit.de/en/12.1/index.html)

# Generated documentation
We can use the `swagger-php` lib. [Doc here](https://github.com/zircote/swagger-php)

# Docker Environment
 We need three environments, each using a specific Docker configuration :
* Development
* Staging
* Production

## Development
This branch will be the starting point for every new implementation.

## Staging
After we finish implementing some features, we merge the `DEV` branch into `STAGING` (without deleting `DEV`). With this environment, we can test the client experience.

## Production
Finally, we do merging of `STAGING` on `PROD`.
It has public access.

# Deployment
For me, there are two possibilities

### Manual Local Setup
Use scripts to start the environments locally.
* `DEV`: Load with the local code base
* `STAGING`: Load by pulling on the `STAGING` branch from the repository
* `PROD`: Load by pulling on the `PROD` branch from the repository

### CI/CD-based Deployment
Local script
* `DEV`: Load with the local code base

Then, remotely via CI/CD:
* `STAGING`: Set up in the CI/CD pipeline to push to a specific Clever Cloud application when the `STAGING` branch is updated.
* `PROD`: Set up in the CI/CD pipeline to push to a specific Clever Cloud application when the `PROD` branch is updated.

**CI/CD** stands for Continuous Integration and Continuous Delivery/Deployment. The configuration is typically done in a YAML file (e.g., `.gitlab-ci.yml`, `.github/workflows/main.yml`) located in the root of the repository. This allows scripting automated tasks within the pipeline on platforms like GitLab or GitHub.

Example that concerned us:
```yaml
# Example testing PHP 8.2 (adjust version as needed)
test:php8.2:
  image: php:8.2 # Use an appropriate PHP image
  script:
    - composer install # Often needed before running tests
    - phpunit --configuration phpunit.xml # Assuming default config name
```

We can configure the CI/CD pipeline to automatically run unit and integration tests. If they do not pass, we can configure the system to block merge requests. Since CI/CD scripts often use shell commands, we can automate almost any command-line task.
